/**
THIS CODE CAN BE USED TO RUN BLDC/PMDC MOTORS BOTH IN FORWARD AND BACKWARD DIRECTION CONTINUOUSLY
THIS CODE CAN ALSO BE USED TO EXTEND AND RETRACT LINEAR ACTUATOR CONTINUOUSLY 
DELAY MUST BE CHANGED AND SET ACCORDINGLY TO THE EXTENSION AND RETRACTION TIME OF LINEAR ACTUATOR

L298 MOTOR DRIVER USED

PIN CONFIGURATION
12V OF L298 TO POSITIVE TERMINAL OF EXTERNAL POWER SOURCE
GND SHOULD BE SHORTED WITH ARDUINO GND AND EXTERNAL POWER SOURCE GND

OUT1 USED OF POSITIVE TERMINAL OF MOTOR
OUT2 USED OF NEGATIVE TERMINAL OF MOTOR

IN1 SHORTED WITH DIGITAL PIN 4 OF ARDUINO
IN2 SHORTED WITH DIGITAL PIN 5 OF ARDUINO

TO CONTROL SPEED
REMOVE JUMPER FROM EA PIN ON MOTOR DRIVER
SHORTED EA PIN WITH PWM DIGITAL PIN 9 

IF YOU DONT WANT TO CONTROL SPEED
THEN EA PINS MUST BE SHORTED
AND SPEED CONTROLLING LINES IN CODE MUST BE COMMENTED I.E LINES ---> int SPD_CONTROL_PIN = 9;   pinMode(SPD_CONTROL_PIN, OUTPUT); analogWrite(SPD_CONTROL_PIN, 255);

OUT 3 AND OUT 4 CAN BE USED WITH IN 3 AND IN 4 SHORTED WITH 6, 7 DIGITAL PINS ON ARDUINO


PROGRAMMED BY YASIN


**/


int MOTOR_FWD_PIN = 4;    //SET POSITIVE PIN FOR MOTOR 1
int MOTOR_BWD_PIN = 5;   //SET NEGATIVE PIN FOR MOTOR 1
int SPD_CONTROL_PIN = 9;  //SET SPEED CONTROL (PWM) PIN

void setup()
{
  Serial.begin(9600);
  pinMode(MOTOR_FWD_PIN, OUTPUT);    
  pinMode(MOTOR_BWD_PIN, OUTPUT);
   pinMode(SPD_CONTROL_PIN, OUTPUT);
  
}

void loop(){
analogWrite(SPD_CONTROL_PIN, 255);   //255 = 100% POWER CYCLE or max pwm

//Refer to: 
//https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM
//For PWM values


      digitalWrite(MOTOR_BWD_PIN, LOW);
      Serial.println("Start delay 10 secs");
      delay(10000);                      //THIS LINE CAN BE UNCOMMENTED FOR STOPPING MOTOR FOR 10 SECONDS BEFORE STARTING IN FORWARD DIRECTION

      Serial.println("Starting FWD");
      digitalWrite(MOTOR_FWD_PIN, HIGH);  //START MOTOR IN FORWARD (extend)
      delay(10000);
      Serial.println("Stopping FWD");
      digitalWrite(MOTOR_FWD_PIN, LOW);   //STOP AFTER 10 SECS
      delay(10000);

      Serial.println("Starting BWD");
      digitalWrite(MOTOR_BWD_PIN, HIGH);  //STARTS IN REVERSE AFTER 10 SECONDS (retract) --- WILL RUN IN REVERSE DIRECTION FOR 10 SECONDS 
      delay(10000); //AFTER 10 SECOND, MOTOR STARTS IN FORWARD IMMEDIATELY
      Serial.println("Stopping BWD");
}
